### PR TITLE
Added Telnet support (fixes #6)

### LINKED ISSUE #6: Embed Telnet connector by default
Otherwise one needs to manually drop `crash.connectors.telnet-1.3.0-beta14.jar` + dependencies into `org.crashub~vertx.shell~2.0.4/lib`...

### PR DESCRIPTION
**Pull request by ddossot**
I also fixed this issue in `mod.xml`:

```
[WARNING] DependencySet has nonsensical configuration: useTransitiveDependencies == false
AND useTransitiveFiltering == true. Transitive filtering flag will be ignored.
```

### CODE REVIEW

**Comment by vietj** [comment]
I will look into this soon.

**Comment by ddossot** [comment]
I notice you've released 2.0.5 without this: any reason?

**Comment by vietj** [comment]
I wanted to discuss with you about how it should be included in the mod. What is your motivation for using telnet instead of ssh ?

**Comment by ddossot** [comment]
We SSH in production instances so it makes no sense to SSH again in the console: Telnet makes most sense in that case. Why adding a second SSH connection or another authentication mechanism, when the connection to the instance already provides that?

And no, there's no way we would open CRaSH SSH to the world :smile: One security-tight SSH port per prod instance is all we allow, and I don't think we're the only ones with such policy.

**Comment by vietj** [comment]
thanks for the explanation. this perfectly makes sense in your case.

I will merge it soon, however it will be disabled by default. It would be activated with a property in mod.json . Is it fine for you ?

**Comment by vietj** [comment]
Another option would be to have two mod-shell one with SSH and one with Telnet (I don't see the need to have both SSH and Telnet, at least not yet).

**Comment by ddossot** [comment]
Two mod-shells sound good to me: I too can't think of a case where one would want both SSH and Telnet.

**Pull request closed without merging**
